import fs from "node:fs/promises";
import path from "node:path";
import * as esbuild from "esbuild";
import type { DeviceSDKConfig } from "../config.js";
import { EXIT } from "../exitCodes.js";
import { loadConfig } from "../utils.js";

interface BuildOptions {
	device?: string;
	outdir?: string;
	minify?: boolean;
	sourcemap?: boolean;
	config?: string;
}

const MAX_SCRIPT_SIZE = 1024 * 1024; // 1MB

/**
 * Generates devicesdk-env.d.ts alongside devicesdk.ts with type-safe
 * inter-device RPC types based on the project's device configuration.
 */
export async function generateDeviceTypes(
	config: DeviceSDKConfig,
	configDir: string,
): Promise<void> {
	const devices = Object.entries(config.devices);
	if (devices.length === 0) return;

	const imports: string[] = [];
	const deviceMap: string[] = [];
	const seenClassNames = new Map<string, number>();

	for (const [slug, device] of devices) {
		// Resolve the main path relative to configDir, strip .ts extension for import
		let importPath = device.main;
		if (importPath.endsWith(".ts")) {
			importPath = importPath.slice(0, -3);
		}
		// Ensure it starts with ./ for relative imports
		if (!importPath.startsWith("./") && !importPath.startsWith("../")) {
			importPath = `./${importPath}`;
		}

		// Warn if main looks like a class name instead of a file path
		if (!device.main.includes("/") && !device.main.endsWith(".ts")) {
			console.warn(
				`Warning: Device "${slug}": 'main' looks like a class name, not a file path. ` +
					`Set 'main' to the file path (e.g. './src/devices/${slug}.ts') for correct type generation.`,
			);
		}

		const className = device.entrypoint;
		const count = seenClassNames.get(className) ?? 0;
		seenClassNames.set(className, count + 1);

		if (count === 0) {
			imports.push(`import type { ${className} } from "${importPath}";`);
			deviceMap.push(`\t"${slug}": ${className};`);
		} else {
			const alias = `${className}_${count}`;
			imports.push(
				`import type { ${className} as ${alias} } from "${importPath}";`,
			);
			deviceMap.push(`\t"${slug}": ${alias};`);
		}
	}

	const content = `// Auto-generated by DeviceSDK CLI — do not edit manually.
// Provides type-safe inter-device RPC types for this project.
// Re-run \`devicesdk build\` to regenerate after config changes.

${imports.join("\n")}
import type { GetEnv } from "@devicesdk/core";

export type ProjectDevices = {
${deviceMap.join("\n")}
};

export type Env = GetEnv<ProjectDevices>;
`;

	const outPath = path.join(configDir, "devicesdk-env.d.ts");
	await fs.writeFile(outPath, content);
	console.log("✓ Generated devicesdk-env.d.ts");
}

async function buildDevice(
	deviceId: string,
	entrypoint: string,
	outdir: string,
	options: { minify?: boolean; sourcemap?: boolean },
): Promise<{ size: number; outfile: string }> {
	const outfile = path.join(outdir, `${deviceId}.js`);

	await esbuild.build({
		entryPoints: [entrypoint],
		bundle: true,
		outfile,
		format: "esm",
		target: "es2022",
		platform: "node",
		conditions: ["workerd", "worker", "browser"],
		external: ["cloudflare:workers"],
		minify: options.minify || false,
		sourcemap: options.sourcemap || false,
	});

	const stats = await fs.stat(outfile);
	return { size: stats.size, outfile };
}

function formatSize(bytes: number): string {
	if (bytes < 1024) return `${bytes} B`;
	if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default async function build(options: BuildOptions = {}): Promise<void> {
	try {
		const config = await loadConfig(options.config);
		const configDir = path.dirname(
			options.config
				? path.resolve(process.cwd(), options.config)
				: path.join(process.cwd(), "devicesdk.ts"),
		);
		const outdir = options.outdir
			? path.resolve(process.cwd(), options.outdir)
			: path.join(configDir, ".devicesdk", "build");

		// Generate inter-device RPC type definitions
		await generateDeviceTypes(config, configDir);

		// Create output directory
		await fs.mkdir(outdir, { recursive: true });

		// Filter devices if specific device requested
		let devicesToBuild = Object.entries(config.devices);
		if (options.device) {
			const device = config.devices[options.device];
			if (!device) {
				console.error(
					`✗ Error: Device "${options.device}" not found in config\n`,
				);
				console.error(
					`  Available devices: ${Object.keys(config.devices).join(", ")}`,
				);
				process.exit(EXIT.BUILD_ERROR);
			}
			devicesToBuild = [[options.device, device]];
		}

		if (devicesToBuild.length === 0) {
			console.error("✗ Error: No devices configured\n");
			console.error("  Add devices to your devicesdk.ts configuration file.");
			process.exit(EXIT.BUILD_ERROR);
		}

		let totalSize = 0;
		const results: Array<{ deviceId: string; size: number; error?: string }> =
			[];

		for (const [deviceId, device] of devicesToBuild) {
			const mainFile = path.resolve(configDir, device.main);

			// Check if main file exists
			try {
				await fs.access(mainFile);
			} catch {
				console.error(`✗ ${deviceId}: Main file not found: ${device.main}`);
				results.push({ deviceId, size: 0, error: "Main file not found" });
				continue;
			}

			try {
				const { size } = await buildDevice(deviceId, mainFile, outdir, {
					minify: options.minify,
					sourcemap: options.sourcemap,
				});

				if (size > MAX_SCRIPT_SIZE) {
					console.error(
						`✗ ${deviceId}: Script exceeds maximum size of 1MB (${formatSize(size)})`,
					);
					results.push({ deviceId, size, error: "Script too large" });
					continue;
				}

				console.log(`✓ Built ${deviceId}.js (${formatSize(size)})`);
				results.push({ deviceId, size });
				totalSize += size;
			} catch (error) {
				const message =
					error instanceof Error ? error.message : "Unknown error";
				console.error(`✗ ${deviceId}: Build failed - ${message}`);
				results.push({ deviceId, size: 0, error: message });
			}
		}

		const successCount = results.filter((r) => !r.error).length;
		const failCount = results.filter((r) => r.error).length;

		console.log(
			`\nBuild complete: ${successCount} device${successCount !== 1 ? "s" : ""}, ${formatSize(totalSize)} total`,
		);

		if (failCount > 0) {
			console.error(
				`\n${failCount} device${failCount !== 1 ? "s" : ""} failed to build`,
			);
			process.exit(EXIT.BUILD_ERROR);
		}
	} catch (error) {
		console.error("✗ Error: Build failed\n");
		if (error instanceof Error) {
			console.error(`  ${error.message}`);
		}
		process.exit(EXIT.BUILD_ERROR);
	}
}

export { buildDevice, formatSize };
