packages:
  - "apps/*"
  - "packages/*"
  - "firmware/*"
  - "examples/*"

catalog:
  typescript: 5.9.3
  "@types/node": ^22
  vitest: ^3.2.4
  "@vitest/runner": ^3.2.4
  "@vitest/coverage-istanbul": ^3.2.4
  "@vitest/snapshot": ^3.2.4
  wrangler: ^4.84.1
  tsx: ^4.20.5

catalogs:
  zod3:
    zod: ^3.25.76
  zod4:
    zod: ^4.3.6
  tailwind3:
    tailwindcss: ^3.4.1
  tailwind4:
    tailwindcss: ^4.1.18
