name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test_build:
        name: Build client
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              id: build
              uses: samyarsadat/Pico-Build-Action@v1
              env:
                IOTKIT_WIFI_SSID: "DUMMY_SSID"
                IOTKIT_WIFI_PASSWORD: "DUMMY_PASSWORD"
                IOTKIT_API_TOKEN: "DUMMY_TOKEN"
              with:
                  source_dir: "./"
                  cmake_args: "-DCMAKE_BUILD_TYPE=Debug"

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: iotkit-client
                  path: ${{steps.build.outputs.output_dir}}/iotkit-client.uf2
                  if-no-files-found: error
