// Auto-generated by DeviceSDK CLI - do not edit manually.
// Provides type-safe inter-device RPC types for this project.
// Re-run `devicesdk build` to regenerate after config changes.

import type { ClockDevice } from "./src/devices/clock";
import type { UserWorkerEnv } from "@devicesdk/core";

export type ProjectDevices = {
	"clock": ClockDevice;
};

export type Env = UserWorkerEnv<ProjectDevices>;
