// Auto-generated by DeviceSDK CLI — do not edit manually.
// Provides type-safe inter-device RPC types for this project.
// Re-run `devicesdk build` to regenerate after config changes.

import type { MyDevice } from "./src/devices/button";
import type { GetEnv } from "@devicesdk/core";

export type ProjectDevices = {
	"device": MyDevice;
};

export type Env = GetEnv<ProjectDevices>;
